language: ruby
cache: bundler
sudo: false

notifications:
  email: false

rvm:
  - 2.7.1
  - 2.6.5

gemfile:
  - gemfiles/sinatra_2_1.gemfile
  - gemfiles/sinatra_2_0.gemfile
  - gemfiles/sinatra_1_4.gemfile

env:
  global:
    secure: Zq3YrKeSaVI0U5bcYDDnCOxbQDHPpPmTrNGe0M2qtVwN1tibpULIdZVMGOjJ4C4Ulk8OXqpI63aLkWm7fKIT0bQXvGK+w3bksUIHk2jODHfKb/ZDDfAoKhfU1APXnxcGbw06/FDyihWJFYdxrLZBilnvDmcqVz47DvmFBAlPuQ4=
