language: ruby
cache: bundler
sudo: false

notifications:
  email: false

rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0

gemfile:
  - gemfiles/sinatra_2.gemfile
  - gemfiles/sinatra_1.gemfile

env:
  global:
    secure: Zq3YrKeSaVI0U5bcYDDnCOxbQDHPpPmTrNGe0M2qtVwN1tibpULIdZVMGOjJ4C4Ulk8OXqpI63aLkWm7fKIT0bQXvGK+w3bksUIHk2jODHfKb/ZDDfAoKhfU1APXnxcGbw06/FDyihWJFYdxrLZBilnvDmcqVz47DvmFBAlPuQ4=
